routes/web.php
<?php

use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\PaymentController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('invoices/{id}/done', [InvoiceController::class, 'markasdone'])->name('invoices.markasdone');
    Route::resource('invoices', InvoiceController::class);

    Route::get('/items/{id}', [ItemController::class, 'index'])->name('items.index');
    Route::get('/items/{id}/show', [ItemController::class, 'show'])->name('items.show');
    Route::get('/items/{id}/create', [ItemController::class, 'create'])->name('items.create');
    Route::post('/items/store', [ItemController::class, 'store'])->name('items.store');
    Route::delete('/items/{id}/destroy', [ItemController::class, 'destroy'])->name('items.destroy');

    Route::get('/payments/{id}', [PaymentController::class, 'index'])->name('payments.index');
    Route::get('/payments/{id}/show', [PaymentController::class, 'show'])->name('payments.show');
    Route::get('/payments/{id}/create', [PaymentController::class, 'create'])->name('payments.create');
    Route::post('/payments/store', [PaymentController::class, 'store'])->name('payments.store');
    Route::delete('/payments/{id}/destroy', [PaymentController::class, 'destroy'])->name('payments.destroy');
});

resources/views/sb-components/footer.blade.php
 <!-- Footer -->
 <footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; aqrist 2023</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

resources/views/sb-components/navbar.blade.php
 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

     <!-- Sidebar Toggle (Topbar) -->
     <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
         <i class="fa fa-bars"></i>
     </button>


     <!-- Topbar Navbar -->
     <ul class="navbar-nav ml-auto">

         <div class="topbar-divider d-none d-sm-block"></div>

         <!-- Nav Item - User Information -->
         <li class="nav-item dropdown no-arrow">
             <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                 <img class="img-profile rounded-circle" src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}">
             </a>
             <!-- Dropdown - User Information -->
             <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                 <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                     <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                     Logout
                 </a>
             </div>
         </li>

     </ul>

 </nav>
 <!-- End of Topbar -->

 <!-- Logout Modal-->
 <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
     <div class="modal-dialog" role="document">
         <div class="modal-content">
             <div class="modal-header">
                 <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                 <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                     <span aria-hidden="true">×</span>
                 </button>
             </div>
             <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
             <div class="modal-footer">
                 <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                 <a class="btn btn-primary" href="{{ route('logout') }}"
                     onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">Logout</a>
             </div>
         </div>
     </div>
 </div>


 <!-- Logout form -->
 <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
     @csrf
 </form>

resources/views/sb-components/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('/') }}">
        <div class="sidebar-brand-icon">
            {{-- <i class="fas fa-utensils"></i> --}}
        </div>
        <div class="sidebar-brand-text mx-3">Invoice Manager</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item {{ request()->routeIs('home') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Main Menu
    </div>

    {{-- Nav Item - Tickets --}}
    <li class="nav-item {{ request()->routeIs('invoices.*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('invoices.index') }}">
            <i class="fas fa-fw fa-book"></i>
            <span>Invoices List</span></a>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
{{-- 
    <li class="nav-item {{ request()->routeIs('claim') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('claim') }}">
            <i class="fas fa-fw fa-users"></i>
            <span>Claim E-Ticket</span></a>
    </li> --}}

    {{-- <li class="nav-item {{ request()->routeIs('scan') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('scan') }}">
            <i class="fas fa-fw fa-qrcode"></i>
            <span>Scan</span></a>
    </li> --}}

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->
    <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="{{ url('sb/img/undraw_rocket.svg') }}" alt="...">
        <p class="text-center mb-2"><strong>Kerja kerja kerja!</strong>
        </p>
        <a class="btn btn-success btn-sm" href="">Kerja bang</a>
    </div>

</ul>
<!-- End of Sidebar -->