routes/web.php
<?php

use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\PaymentController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function () {
    Route::get('invoices/{id}/done', [InvoiceController::class, 'markasdone'])->name('invoices.markasdone');
    Route::resource('invoices', InvoiceController::class);

    Route::get('/items/{id}', [ItemController::class, 'index'])->name('items.index');
    Route::get('/items/{id}/show', [ItemController::class, 'show'])->name('items.show');
    Route::get('/items/{id}/create', [ItemController::class, 'create'])->name('items.create');
    Route::post('/items/store', [ItemController::class, 'store'])->name('items.store');
    Route::delete('/items/{id}/destroy', [ItemController::class, 'destroy'])->name('items.destroy');

    Route::get('/payments/{id}', [PaymentController::class, 'index'])->name('payments.index');
    Route::get('/payments/{id}/show', [PaymentController::class, 'show'])->name('payments.show');
    Route::get('/payments/{id}/create', [PaymentController::class, 'create'])->name('payments.create');
    Route::post('/payments/store', [PaymentController::class, 'store'])->name('payments.store');
    Route::delete('/payments/{id}/destroy', [PaymentController::class, 'destroy'])->name('payments.destroy');
});

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Invoice extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'billto',
        'billfrom',
        'invoice_number',
        'start_date',
        'due_date',
        'notes',
        'terms',
        'amount_paid',
        'discount',
        'status',
        'description',
    ];

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    public function items()
    {
        return $this->hasMany(Item::class);
    }

    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($invoice) {
            // Delete associated payments
            $invoice->payments()->delete();
            $invoice->items()->delete();
        });
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Invoice;
use App\Models\Item;
use App\Models\Payment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (request()->ajax()) {
            # code...
            $query = Invoice::orderBy('created_at', 'DESC');

            // Check if the 'status' filter is set
            if (request('status') !== null) {
                $query->where('status', request('status'));
            }

            return Datatables::of($query)
                ->addColumn('total_amount', function ($item) {
                    $amount = Item::where('invoice_id', $item->id)->sum('price');
                    $discount = $item->discount;
                    $total_amount = ($amount - $discount);

                    return $total_amount;
                })
                ->addColumn('balance_due', function ($item) {
                    $subtotal = Item::where('invoice_id', $item->id)->sum('price');
                    $discount = $item->discount;
                    $amount_paid = Payment::where('invoice_id', $item->id)->sum('amount_paid');
                    $balance_due = ($subtotal - $discount) - $amount_paid;

                    return $balance_due;
                })
                ->editColumn('amount_paid', function ($item) {
                    $def = $item->amount_paid;
                    $total_payment = Payment::where('invoice_id', $item->id)->sum('amount_paid');
                    $grand_total = $def + $total_payment;

                    return $grand_total;
                })
                ->editColumn('status', function ($item) {
                    if ($item->status == '0') {
                        # code...
                        return '<i class="fas fa-fw fa-times"></i>';
                    } elseif ($item->status == '1') {
                        # code...
                        return '<i class="fas fa-fw fa-check"></i>';
                    }
                })
                ->addColumn('action', function ($item) {
                    return '
                    <a class="btn btn-sm btn-info m-1" href="' . route('invoices.edit', $item->id)  . '">
                        <i class="fas fa-fw fa-edit"></i>
                    </a>
                    <a class="btn btn-sm btn-info m-1" href="' . route('invoices.show', $item->id)  . '">
                        <i class="fas fa-fw fa-book"></i>
                    </a>
                    <a class="btn btn-sm btn-warning m-1" href="' . route('items.index', $item->id)  . '">
                        <i class="fas fa-fw fa-bookmark"></i>
                    </a>
                    <a class="btn btn-sm btn-success m-1" href="' . route('payments.index', $item->id)  . '">
                        <i class="fas fa-fw fa-dollar-sign"></i>
                    </a>
                    <a class="btn btn-sm btn-danger m-1" href="#" data-toggle="modal" data-target="#deleteModal' . $item->id . '">
                        <i class="fas fa-fw fa-trash"></i>
                    </a>

                    <!-- Delete Modal -->
                        <div class="modal fade" id="deleteModal' . $item->id . '" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel' . $item->id . '" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel' . $item->id . '">Confirm Deletion</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you want to delete this item?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
                                        <form method="POST" action="' . route('invoices.destroy', $item->id) . '" style="display: inline;">
                                            ' . csrf_field() . '
                                            ' . method_field('DELETE') . '
                                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                            ';
                })
                ->rawColumns(['action', 'total_amount', 'status', 'balance_due'])
                ->make(true);
        }
        return view('pages.invoices.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.invoices.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // Validation logic goes here
        $validatedData = $request->validate([
            'billto' => 'required|string',
            'billfrom' => 'required|string',
            'start_date' => 'required|string',
            'due_date' => 'required|string',
            'notes' => 'required|string',
            'terms' => 'required|string',
            'discount' => 'nullable|string',
            'invoice_number' => 'string',
            'description' => 'string',
        ]);


        $validatedData['invoice_number'] = $this->generateInvoiceNumber();

        Invoice::create($validatedData);

        if ($request->has('save_only')) {
            # code to back and save
            return back()->with('success', 'Invoice added Succesfully!');
        } elseif ($request->has('save_and_back')) {
            # code to exit and save
            return redirect()->route('invoices.index')->with('success', 'Invoice added Succesfully!');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $invoice = Invoice::findOrFail($id);
        $items = Item::where('invoice_id', $id)->get();
        $subtotal = Item::where('invoice_id', $id)->sum('price');
        $paid = Payment::where('invoice_id', $id)->sum('amount_paid');

        $payments = Payment::where('invoice_id', $id)->get();

        return view('pages.invoices.show')->with([
            'invoice' => $invoice,
            'items' => $items,
            'subtotal' => $subtotal,
            'paid' => $paid,
            'payments' => $payments,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $invoice = Invoice::findOrFail($id);

        return view('pages.invoices.edit', compact('invoice'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $invoice = Invoice::findOrFail($id);

        $invoice->description = $request->input('description');
        $invoice->discount = $request->input('discount');

        $invoice->save();

        return redirect()->route('invoices.index')->with('success', 'Invoice updated Succesfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        try {
            $invoice = Invoice::findOrFail($id);
            $invoice->delete();

            return redirect()->route('invoices.index')->with('success', 'Invoice deleted successfully');
        } catch (\Exception $e) {
            return redirect()->route('invoices.index')->with('error', 'Error deleting invoice, ' . $e . '');
        }
    }

    public function generateInvoiceNumber()
    {
        // Get the current year
        $year = date('Y');

        // Get the last invoice number from the database
        $lastInvoice = DB::table('invoices')->latest()->first();

        // Extract the sequential part of the last invoice number
        $lastSequential = $lastInvoice ? intval(substr($lastInvoice->invoice_number, -5)) : 0;

        // Increment the sequential part
        $newSequential = $lastSequential + 1;

        // Pad the sequential part with leading zeros
        $paddedSequential = str_pad($newSequential, 5, '0', STR_PAD_LEFT);

        // Create the new invoice number
        $invoiceNumber = "INV-$year-$paddedSequential";

        return $invoiceNumber;
    }

    public function markasdone($id)
    {
        $invoice = Invoice::findOrFail($id);
        $invoice->status = true;
        $invoice->save();
        return back()->with('success', 'succesfully completed!');
    }
}

resources/views/pages/invoices/create.blade.php
@extends('layouts.sb')

@section('heading')
    Invoices
@endsection

@section('content')
    {{-- notification --}}
    @include('layouts/flash-message')
    {{-- end notification --}}

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card border-left-primary shadow">

                <div class="card-header">
                    Add new Invoice
                </div>

                <div class="card-body">
                    <form action="{{ route('invoices.store') }}" method="post" enctype="multipart/form-data">
                        @csrf

                        <!-- Create row then inside there are 2 col md 6 -->
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="billto">Bill To:</label>
                                    <input type="text" id="billto" name="billto"
                                        class="form-control @error('billto') is-invalid @enderror"
                                        value="{{ old('billto') }}" required>
                                    @error('billto')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="billfrom">Bill From:</label>
                                    <input type="text" id="billfrom" name="billfrom"
                                        class="form-control @error('billfrom') is-invalid @enderror"
                                        value="{{ old('billfrom') }}" required>
                                    @error('billfrom')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="description">Description:</label>
                                    <input type="text" id="description" name="description"
                                        class="form-control @error('description') is-invalid @enderror"
                                        value="{{ old('description') }}" required>
                                    @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="start_date">Start Date:</label>
                                    <input type="date" id="start_date" name="start_date"
                                        class="form-control @error('start_date') is-invalid @enderror"
                                        value="{{ old('start_date') }}" required>
                                    @error('start_date')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="due_date">Due Date:</label>
                                    <input type="date" id="due_date" name="due_date"
                                        class="form-control @error('due_date') is-invalid @enderror"
                                        value="{{ old('due_date') }}" required>
                                    @error('due_date')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="notes">Notes:</label>
                                    <input type="text" id="notes" name="notes"
                                        class="form-control @error('notes') is-invalid @enderror"
                                        value="{{ old('notes') }}" required>
                                    @error('notes')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="terms">Terms:</label>
                                    <input type="text" id="terms" name="terms"
                                        class="form-control @error('terms') is-invalid @enderror"
                                        value="{{ old('terms') }}" required>
                                    @error('terms')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="discount">Discount *on rupiah:</label>
                                    <input type="number" id="discount" name="discount"
                                        class="form-control @error('discount') is-invalid @enderror"
                                        value="{{ old('discount') }}">
                                    @error('discount')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                        </div>

                        <div class="form-group">
                            <button type="submit" name="save_only" class="btn btn-primary">Save</button>
                            <button type="submit" name="save_and_back" class="btn btn-info">Save and Back</button>
                        </div>

                    </form>
                </div>


            </div>
        </div>
    </div>
@endsection

resources/views/pages/invoices/edit.blade.php
@extends('layouts.sb')

@section('heading')
    Invoices
@endsection

@section('content')
    {{-- notification --}}
    @include('layouts/flash-message')
    {{-- end notification --}}

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card border-left-primary shadow">

                <div class="card-header">
                    Edit Invoice
                </div>

                <div class="card-body">
                    <form action="{{ route('invoices.update', $invoice->id) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <!-- Create row then inside there are 2 col md 6 -->
                        <div class="row mb-3">

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="description">Description:</label>
                                    <input type="text" id="description" name="description"
                                        class="form-control @error('description') is-invalid @enderror"
                                        value="{{ $invoice->description }}" required>
                                    @error('description')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="discount">Discount *on rupiah:</label>
                                    <input type="number" id="discount" name="discount"
                                        class="form-control @error('discount') is-invalid @enderror"
                                        value="{{ $invoice->discount }}">
                                    @error('discount')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>


                        </div>

                        <div class="form-group">
                            <button type="submit" name="save_only" class="btn btn-primary">Update</button>
                            <button type="submit" name="save_and_back" class="btn btn-info">Update and Back</button>
                        </div>

                    </form>
                </div>


            </div>
        </div>
    </div>
@endsection

resources/views/pages/invoices/index.blade.php
@extends('layouts.sb')

@section('heading')
    Invoices
@endsection

{{-- debug {{ $items }} --}}

@section('content')
    {{-- notification --}}
    @include('layouts/flash-message')
    {{-- end notification --}}

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12 mb-3">
            <div class="card shadow">
                <div class="card-header">
                    Filter by Status:
                </div>
                <div class="card-body">
                    <form id="filter-form">
                        <select name="status" id="status" class="form-control mb-3">
                            <option value="">All</option>
                            <option value="0">Not Done</option>
                            <option value="1">Done</option>
                        </select>
                        <button type="submit" class="btn btn-primary">Apply Filter</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="card shadow">

                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">Invoices</h6>
                </div>

                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-12">
                            <a href="{{ route('invoices.create') }}" class="btn btn-primary">Add new</a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover scroll-horizontal-vertical" id="crudTable"
                            width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="d-none">Id</th>
                                    <th>Invoice Number</th>
                                    <th>Desc</th>
                                    <th>Total Amount</th>
                                    <th>Balance Due</th>
                                    <th>Amount Paid</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>

                </div>


            </div>
        </div>
    </div>
@endsection

@push('addon-script')
    <script>
        // Initialize DataTable
        var datatable = $('#crudTable').DataTable({
            processing: true,
            serverSide: true,
            paging: true,
            ajax: {
                url: '{{ route('invoices.index') }}',
                data: function(d) {
                    d.status = $('#status').val(); // Pass the selected status as a filter parameter
                }
            },
            columns: [{
                    data: 'id',
                    name: 'id',
                    visible: false
                },
                {
                    data: 'invoice_number',
                    name: 'invoice_number'
                },
                {
                    data: 'description',
                    name: 'description'
                },
                {
                    data: 'total_amount',
                    name: 'total_amount',
                    render: function(data, type, row) {
                        // Format the amount as currency
                        return 'Rp. ' + number_format(data, 2, ',', '.');
                    }
                },
                {
                    data: 'balance_due',
                    name: 'balance_due',
                    render: function(data, type, row) {
                        // Format the amount as currency
                        return 'Rp. ' + number_format(data, 2, ',', '.');
                    }
                },
                {
                    data: 'amount_paid',
                    name: 'amount_paid',
                    render: function(data, type, row) {
                        // Format the amount as currency
                        return 'Rp. ' + number_format(data, 2, ',', '.');
                    }
                },
                {
                    data: 'status',
                    name: 'status',
                    orderable: false,
                    searchable: false,
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false,
                    width: '15%'
                },
            ]
        });

        // Handle filter form submission
        $('#filter-form').on('submit', function(e) {
            e.preventDefault();
            datatable.ajax.reload(); // Reload the DataTable with the selected filter
        });
    </script>
@endpush